### ISSUE TITLE
KeyError: 'clusterpermission' when running local docker-compose

### ISSUE THREAD

**Issue by johanneshk** [BLSQ/openhexa-app#150]
Hello,
thanks for this very interesting projects!

I have trouble running the local docker-compose project:

First issue I had was in the initial build step:
```
Step 10/17 : RUN --mount=type=cache,mode=0755,target=/root/.cache/pip pip install -r requirements.txt
2 errors occurred:
	* Status: the --mount option requires BuildKit. Refer to https://docs.docker.com/go/buildkit/ to learn how to build images with BuildKit enabled, Code: 1
	* Status: the --mount option requires BuildKit. Refer to https://docs.docker.com/go/buildkit/ to learn how to build images with BuildKit enabled, Code: 1

```
I was able to circumvent this by removing the --mount option. Then next issue I encountered when running 'app fixtures':

``` 
...
Applying visualizations.0003_indexes_django_4... OK
Superuser created successfully.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/apps/config.py", line 267, in get_model
    return self.models[model_name.lower()]
KeyError: 'clusterpermission'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/serializers/python.py", line 155, in _get_model
    return apps.get_model(model_identifier)
  File "/usr/local/lib/python3.9/site-packages/django/apps/registry.py", line 211, in get_model
    return app_config.get_model(model_name, require_ready=require_ready)
  File "/usr/local/lib/python3.9/site-packages/django/apps/config.py", line 269, in get_model
    raise LookupError(
LookupError: App 'connector_airflow' doesn't have a 'clusterpermission' model.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/code/manage.py", line 22, in <module>
    main()
  File "/code/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 425, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 373, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 417, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/loaddata.py", line 78, in handle
    self.loaddata(fixture_labels)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/loaddata.py", line 138, in loaddata
    self.load_label(fixture_label)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/loaddata.py", line 214, in load_label
    for obj in objects:
  File "/usr/local/lib/python3.9/site-packages/django/core/serializers/json.py", line 70, in Deserializer
    yield from PythonDeserializer(objects, **options)
  File "/usr/local/lib/python3.9/site-packages/django/core/serializers/python.py", line 93, in Deserializer
    Model = _get_model(d["model"])
  File "/usr/local/lib/python3.9/site-packages/django/core/serializers/python.py", line 157, in _get_model
    raise base.DeserializationError("Invalid model identifier: '%s'" % model_identifier)
django.core.serializers.base.DeserializationError: Problem installing fixture '/code/hexa/plugins/connector_airflow/fixtures/demo.json': Invalid model identifier: 'connector_airflow.clusterpermission'
```

I tried main branch and 0.23.2 release tag. I'm on Manjaro Linux

Docker version 20.10.12, build e91ed5707e
Docker Compose version 2.2.3

Any ideas? Thanks!

**Comment by pvanliefland** [comment]
Hi @johanneshk ! 

OpenHexa is still a young project, I think you are one of the first persons outside our organization to try running the software. You might encounter issues here and there but we will do our best to assist you :)

Regarding the build issue, I think you need to enable Buildkit. Could you try following [those instructions](https://docs.docker.com/develop/develop-images/build_enhancements/#to-enable-buildkit-builds) and let me know if it works? I'll update the docs accordingly.

For the fixtures, I think we recently broke them, let me check and come back to you.

Just out of curiosity, what use case do you have in mind for OpenHexa?

**Comment by pvanliefland** [comment]
I've just pushed a fix for the fixtures in `main`. You should be good to go. I'm keeping the issue open in case you encounter additional issues during installation.

**Comment by johanneshk** [comment]
Thanks! It's working now. 

We've been talking recently with one of your colleagues about a possible collaboration / integration with your platform in CIV, Burkina Faso, DRC and I wanted to take a look firsthand ;) . Also, I love that this is build on Django, I have fond memories of a previous project built on Django. Seeing the database migrations scroll by was a trip down memory lane...
